# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(default='File1', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
