# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_post_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='output',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
