# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20160420_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='output',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
