# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20160420_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='output',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
