# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_auto_20160424_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d'),
        ),
    ]
