# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_auto_20160424_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
