# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0018_auto_20160424_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='output',
        ),
        migrations.AddField(
            model_name='post',
            name='snpeffoutput',
            field=models.FileField(null=True, upload_to='.'),
        ),
        migrations.AddField(
            model_name='post',
            name='vcfoutput',
            field=models.FileField(null=True, upload_to='.'),
        ),
    ]
