# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0019_auto_20160425_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='snpeffoutput',
        ),
        migrations.AddField(
            model_name='post',
            name='snpeffhtmloutput',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='snpeffvcfoutput',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='vcfoutput',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
