# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0020_auto_20160425_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snpeffhtmlmissenseoutput',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
